// Presets are named bundles of field parameters + a seed. Clicking one in the
// gallery loads the exact configuration, so the artwork is fully reproducible.

export const PRESETS = [
  {
    id: "aurora",
    name: "Aurora",
    blurb: "Slow ribbons folding over a cold sky.",
    config: {
      seed: "aurora-204",
      palette: "tide",
      particles: 1400,
      noiseScale: 0.0016,
      speed: 1.1,
      persistence: 0.06,
      lineWidth: 1.1,
      symmetry: "mirror-x",
      curl: 1.0,
    },
  },
  {
    id: "kiln",
    name: "Kiln",
    blurb: "Heat shimmer rising through ember light.",
    config: {
      seed: "kiln-77",
      palette: "ember",
      particles: 2000,
      noiseScale: 0.0028,
      speed: 1.6,
      persistence: 0.04,
      lineWidth: 0.9,
      symmetry: "none",
      curl: 1.4,
    },
  },
  {
    id: "bloom",
    name: "Bloom",
    blurb: "Fourfold symmetry, petals of orchid ink.",
    config: {
      seed: "bloom-512",
      palette: "orchid",
      particles: 2600,
      noiseScale: 0.0022,
      speed: 0.9,
      persistence: 0.05,
      lineWidth: 1.0,
      symmetry: "quad",
      curl: 1.2,
    },
  },
  {
    id: "kelp",
    name: "Kelp",
    blurb: "Tall green currents in a still tide pool.",
    config: {
      seed: "kelp-31",
      palette: "meadow",
      particles: 1800,
      noiseScale: 0.0018,
      speed: 1.3,
      persistence: 0.07,
      lineWidth: 1.3,
      symmetry: "mirror-y",
      curl: 0.8,
    },
  },
  {
    id: "graphite",
    name: "Graphite",
    blurb: "A monochrome study in pencil drift.",
    config: {
      seed: "graphite-9",
      palette: "graphite",
      particles: 2200,
      noiseScale: 0.0024,
      speed: 1.0,
      persistence: 0.05,
      lineWidth: 0.8,
      symmetry: "none",
      curl: 1.0,
    },
  },
  {
    id: "kaleido",
    name: "Kaleido",
    blurb: "Six-axis mirror, a solar mandala.",
    config: {
      seed: "kaleido-360",
      palette: "solar",
      particles: 3000,
      noiseScale: 0.003,
      speed: 1.2,
      persistence: 0.045,
      lineWidth: 0.9,
      symmetry: "kaleido",
      curl: 1.5,
    },
  },
];
